version: '2'
services:
  web:
    restart: always
    build: ./main_service
    ports:
     - "80:5000"
    links:
        - postgresdb
    depends_on:
        - postgresdb
  postgresdb:
    image: postgres:latest
    restart: always
    container_name: "postgresdb"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    volumes:
      - ../data/postgresql_data:/var/lib/postgresql/data
    ports:
    - 5432:5432